use super::shell::ShellType;
use crate::catalog::types::AliasCatalog;
use crate::cli::interaction::InteractionMode;
use crate::cli::sync::{ShellSyncCommand, SyncCommand};
use crate::core::sync::{
    CATALOG_REVISION_ENV_VAR, MANAGED_ALIASES_ENV_VAR, generate_reconciliation_script,
};
use crate::core::{Failure, Outcome};
use log::warn;

pub fn handle_sync(_cmd: SyncCommand) -> Result<Outcome, Failure> {
    warn!("Run 'aliasmgr sync' through the shell integration generated by 'aliasmgr init'.");
    Ok(Outcome::NoChanges)
}

pub fn handle_shell_sync(
    catalog: &AliasCatalog,
    shell: &ShellType,
    cmd: ShellSyncCommand,
    interaction_mode: InteractionMode,
) -> String {
    let managed_aliases = std::env::var(MANAGED_ALIASES_ENV_VAR).unwrap_or_default();
    let applied_revision = std::env::var(CATALOG_REVISION_ENV_VAR).unwrap_or_default();

    generate_reconciliation_script(
        catalog,
        shell,
        &managed_aliases,
        &applied_revision,
        cmd.if_changed && interaction_mode != InteractionMode::Force,
    )
}

#[cfg(test)]
#[cfg_attr(coverage_nightly, coverage(off))]
mod tests {
    use super::*;
    use crate::catalog::types::Alias;
    use temp_env::with_vars;

    #[test]
    fn shell_sync_uses_terminal_state_from_environment() {
        let mut catalog = AliasCatalog::new();
        catalog.aliases.insert(
            "current".into(),
            Alias::new("echo current".into(), None, true, false),
        );

        with_vars(
            [
                (MANAGED_ALIASES_ENV_VAR, Some("old")),
                (CATALOG_REVISION_ENV_VAR, Some("old-revision")),
            ],
            || {
                let script = handle_shell_sync(
                    &catalog,
                    &ShellType::Bash,
                    ShellSyncCommand { if_changed: true },
                    InteractionMode::Interactive,
                );
                assert!(script.contains("unalias -- 'old'"));
                assert!(script.contains("alias -- 'current=echo current'"));
            },
        );
    }
}
